services:
  postgres:
    image: postgres:15-alpine
    container_name: rpps_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}  # Mapeia para DB_USERNAME do seu .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Mapeia para DB_PASSWORD
      POSTGRES_DB: postgres # Nome fixo do banco (ou use uma variável se preferir)
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} # Do seu .env
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} # Do seu .env
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: